### ISSUE TITLE
Error: Unknown DCE RPC fault status code: 00000721

### ISSUE THREAD

**Issue by cmjlove1** [Ridter/atexec-pro#2]
师傅 你好，我使用kerberos ST票据进行执行命令，atexec-pro出现错误
![image](https://github.com/Ridter/atexec-pro/assets/88427245/cccbf6e5-b486-4a37-a231-24a9d822d151)
但是Imapcket原版的atexec可以执行成功
![image](https://github.com/Ridter/atexec-pro/assets/88427245/73118ede-1de8-4b96-83d0-f91aed2c094d)
请问下这是什么原因呢？

**Comment by Ridter** [comment]
加一个debug看看呢
